### PR TITLE
Join media queries to comma separated string

### PR DESCRIPTION
**Pull request by redhorn**

### CODE REVIEW

**Comment by jonkemp** [comment]
Tests are failing. Please fix.

**Comment by redhorn** [comment]
The font-face.css test fails in master. Any idea why?

**Comment by jonkemp** [comment]
@redhorn tests pass for me. Are you on a PC by chance?

**Comment by redhorn** [comment]
@jonkemp I got a fresh copy of the code and installed gulp 4. So now it's working :)

**Review by jonkemp — APPROVED** [review]

**Pull request merged**
